source 'https://github.com/CocoaPods/Specs.git'

target 'Flannel', :exclusive => true do
  pod "Flannel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Flannel", :path => "../"  
end
